### ISSUE TITLE
Transaction Signing Error in React Native Blink SDK

### ISSUE THREAD

**Issue by codewithmide** [dialectlabs/blinks-react-native#9]
# Transaction Signing Error in React Native Blink SDK

## Description
When attempting to sign a transaction using the React Native Blink SDK, I consistently encounter the following error:

```
ERROR  Failed to sign transaction: [Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.
[[33,35],[1,0],[[409,100,1725806713262,false]],2713]]
```

This error occurs specifically during the `signTransaction` process in the wallet adapter implementation.

## Environment
- React Native version: 0.75.2
- @dialectlabs/blinks version: 0.9.3
- @dialectlabs/blinks-react-native version: 0.2.1
- @solana-mobile/mobile-wallet-adapter-protocol version: 2.0.0
- @solana-mobile/mobile-wallet-adapter-protocol-web3js version: 2.0.0
- @solana/web3.js version: 1.74.0

## Steps to Reproduce
1. Implement the Blink SDK in a React Native application.
2. Attempt to sign a transaction using the provided wallet adapter.
3. The error occurs consistently when `signTransaction` is called.

## Code
Here's the relevant part of my implementation:

```javascript
signTransaction: async (tx: string, context: ActionContext) => {
  try {
    const transactionBuffer = Buffer.from(tx, 'base64');
    let transaction: Transaction | VersionedTransaction;

    try {
      transaction = Transaction.from(transactionBuffer);
    } catch (e) {
      transaction = VersionedTransaction.deserialize(transactionBuffer);
    }

    const signedTransaction = await transact(async (wallet: { signTransactions: (arg0: { transactions: (Transaction | VersionedTransaction)[]; }) => [any] | PromiseLike<[any]>; }) => {
      const [signed] = await wallet.signTransactions({
        transactions: [transaction],
      });

      if (!signed) {
        throw new Error("Failed to sign transaction");
      }

      return signed;
    });

    let serializedTransaction: string;
    if (signedTransaction instanceof Transaction) {
      serializedTransaction = signedTransaction.serialize().toString('base64');
    } else if (signedTransaction instanceof VersionedTransaction) {
      serializedTransaction = Buffer.from(signedTransaction.serialize()).toString('base64');
    } else {
      throw new Error("Unknown transaction type");
    }
    
    return { signature: serializedTransaction };
  } catch (error: any) {
    console.error('Failed to sign transaction:', error);
    return { error: error.message || 'Unknown error occurred during signing' };
  }
},
```

## Expected Behavior
The transaction should be signed successfully without throwing an error.

## Actual Behavior
The signing process fails with the error message mentioned above, indicating a mismatch in field sizes.

## Additional Context
- This error occurs consistently across different blink transactions.
- The error message suggests a potential mismatch in data structure or formatting between the JavaScript side and the native side of the bridge.
- I've verified that the transaction object is correctly formed before attempting to sign it.

## Possible Causes
1. Incompatibility between the versions of @solana/web3.js and the mobile wallet adapter libraries.
2. Incorrect serialization or deserialization of the transaction object.
3. Mismatch in expected data structure between the JS and native sides of the React Native bridge.

## Questions
1. Are there any known issues with these specific versions of the libraries used?
2. Is there a recommended way to debug the transaction object before it's passed to the signing function?
3. Are there any additional steps or checks I should implement in my `signTransaction` function?

Any assistance or guidance on resolving this issue would be greatly appreciated. Thank you for your time and support!

**Comment by zhelezkov** [comment]
Hey, thanks for report.
It seems like this issue is not relevant to our library, because error is thrown from your code and coming from another library you use.
I advice you to first try to sign transaction without blinks library, and then connect a working sign transaction code with blinks library
